spring:
  application:
    name: demo-built
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
    username: ${db_user}
    password: ${db_pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update